name: pharokka_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython==1.78
  - phanotate==1.5.0
  - mmseqs2==13.45111
  - trnascan-se==2.0.9
  - hhsuite==3.3.0
  - emboss==6.6.0
