name: pharokka_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython
  - phanotate>=1.5.0
  - mmseqs2>=13.45111
  - trnascan-se>=2.0.9
  - prodigal>=2.6.3
  - minced>= 0.4.2
  - aragorn>=1.2.41
  - bcbio-gff>= 0.6.9
  - abricate=1.0.0

