package:
  name: "phrokka"
  version: "0.1.0"

source:
  git_rev: v0.1.0
  git_url: https://github.com/gbouras13/phrokka

requirements:
 run:
    - python==3.9.7
    - bump2version==1.0.1
    - wheel==0.37.0
    - watchdog==2.1.6
    - flake8==4.0.1
    - tox==3.24.4
    - coverage==6.2
    - Sphinx==4.3.1
    - twine==3.7.1
    - pytest==6.2.5
    - biopython==1.79
    - phanotate==1.5.0
    - mmseqs2==13.45111
    - trnascan-se==2.0.9

about:
  home: https://github.com/gbouras13/phrokka
  license: MIT
  license_familY: MIT
  license_file: LICENSE
  summary: "Quick Phage annotations"

extra:
  recipe-maintainers:
    - gbouras13