site_name: pharokka
site_url: "https://github.com/gbouras13/pharokka"
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - bash
        - shell
        - python
nav:
    - ABOUT:
      - Overview: index.md
      - Why Use pharokka?: reasons.md
    - RUNNING:
      - Install: install.md
      - Usage: run.md
    - OUTPUT:
      - Output: output.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets